baseURL: "https://betolink.dev"
title: "blog"
paginate: 5
theme: PaperMod
ignoreFiles:
  - \.qmd$
  - \.ipynb$

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-KCME2LBMDG

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: About
          url: about
          weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "@betolink personal blog"
  author: "@betolink"
  comments: true
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images: ["papermod-cover.png"]

  profileMode:
    enabled: enabled
    title: "Luis López"
    subtitle: "Software Engineer and World Wanderer"
    imageUrl: "images/profile.png"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Luis Lopez"
    Content: >
      Welcome to my personal blog about tech, politics and world traveling.

  socialIcons:
    - name: github
      url: "https://github.com/betolink"
    - name: twitter
      url: "https://twitter.com/betolink"
    - name: RsS
      url: "index.xml"

  # server:
  #   headers:
  #     - for: /**
  #       values:
        # Content-Security-Policy: default-src localhost:1313
        # Referrer-Policy: strict-origin-when-cross-origin
        # X-Content-Type-Options: nosniff
        # X-Frame-Options: DENY
        # X-XSS-Protection: 1; mode=block
  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: false
    lineNos: true
    hl_Lines: ""
    lineNoStart: 1
    noClasses: false
    style: monokai
    tabWidth: 4
    # style: solarized-dark

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
